# Generated by Django 4.0.5 on 2022-06-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_data_subject_name_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_name',
            name='description',
            field=models.TextField(),
        ),
    ]
