# Generated by Django 4.0.5 on 2022-06-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_question_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_name',
            name='language',
        ),
        migrations.RemoveField(
            model_name='subject_name',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default='as', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Subject_name',
        ),
    ]
