# Generated by Django 4.0.5 on 2022-06-14 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_subject_name_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='variants',
            new_name='Subject',
        ),
    ]
